### ISSUE TITLE
Error: Cannot find module 'swagger-schema-official/schema'

### ISSUE THREAD

**Issue by moee** [BigstickCarpet/swagger-server#8]
I tried to set up a Docker container that runs the swagger server. For this I followed the instructions on https://www.npmjs.com/package/swagger-server. 

**Environment**

*index.js:*

    var swagger = require('swagger-server');
    var server = new swagger.Server();
    server.parse('PetStore.yaml');
    server.listen(8000, function() { console.log('running'); });

*PetStore.yaml:*

https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml

*Dockerfile:*

    FROM node
    WORKDIR /src
    RUN npm install swagger-server
    COPY index.js /src/index.js
    COPY PetStore.yaml /src/PetStore.yaml
    CMD ["node", "index.js"]

Putting it all together:

`docker build -t swagger-server . && docker run swagger-server`

**Expected behavior**

The swagger server should be executed.

**Actual behavior**

The following exception is thrown:

    module.js:338
        throw err;
              ^
    Error: Cannot find module 'swagger-schema-official/schema'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at /src/node_modules/swagger-server/node_modules/swagger-parser/index.js:12:23
        at Object.<anonymous> (/src/node_modules/swagger-server/node_modules/swagger-parser/index.js:542:3)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)

**Additional information**

I also tried to install the node package `swagger-schema-official` in versions 1.2.0 and 2.0, but to no avail.

**Comment by moee** [comment]
On a side note: Running the `swagger-server-samples` works as expected.

**Comment by BigstickCarpet** [comment]
Thanks for pointing this out.  It's fixed now.

The installation instructions said to either use `npm install swagger-server` or `npm install swagger-server@0.0.x`. The latter one **always** worked, since you're explicitly specifying the `0.0.x` tag.  The former one **sometimes** worked, depending on the version of NPM you have instead.  Since no tag is specified, some versions of NPM choose to install the `latest` version (which is the `1.0.0-alpha`), but other versions of NPM choose to install the latest _released_ version (which is `0.0.x`).

So, I've updated the instructions to always explicitly specify the tag.  Either use `npm install swagger-server@latest` or `npm install swagger-server@0.0.x`.

**Comment by moee** [comment]
Thanks for your reply.

However, if I change the docker file to `npm install swagger-server@0.0.x` I still get the same error message (`Error: Cannot find module 'swagger-schema-official/schema'`).

**Comment by BigstickCarpet** [comment]
I just pushed a new version (`0.0.9`) that I _think_ fixes the problem.  It's a dependency-resolution issue with the new version of NPM.

Can you give it a try and let me know if it works for you?

**Comment by moee** [comment]
Now it works. Thanks!
